version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: achats-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: achats-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: achats
      MYSQL_USER: achatsuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./app/db.sql:/docker-entrypoint-initdb.d/db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: achats-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: {}
